version: '3.9'
services:

  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/
    environment:
      POSTGRES_DB: renderfarm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 09po:L?>
      #restart: always
    networks:
      - render-localhost

  back:
    image: newaldan/renderfarm
    container_name: back
    depends_on:
      - db
    #restart: always
    ports:
      - "8075:8075"
      - "8983:8983"
    environment:
      #DB_USER: postgres
      #DB_PASSWORD: 09po:L?>
      DB_HOST: db
    networks:
      - depo-localhost

  front:
    image: aitonik/render
    container_name: front
    depends_on:
      - db
      - back
    ports:
      - "3000:3000"
    #restart: always
    stdin_open: true
    networks:
      - render-localhost

networks:
  render-localhost:
    driver: bridge

volumes:
  db-data: